### ISSUE TITLE
Cannot pass FinishedTxData.txId to parent code after calling openContractCall

### ISSUE THREAD

**Issue by PUN-app** [hirosystems/connect#171]
Why does openContractCall returns Promise\<void\> instead of returning Promise\<FinishedTxData\>?!?  The onFinish has no context, so can't pull the tx data out with a 'this.blah='.  The promise is called after the onFinish, and that has full context to the object it is called within.  But, cuz it is a void promise, can't use that to get the txId.

**Comment by PUN-app** [comment]
I found a workaround.  But, I highly recommend you change your promise to return FinishedTxData.  

```typescript
type ContractCallExtendedOptions = ContractCallRegularOptions & {
  finishedTxData?: FinishedTxData;
}

onFinishMethod(data: FinishedTxData) {
    this.finishedTxData = data;
}
```

**Comment by kyranjamie** [comment]
This would be a very welcome improvement.

@PUN-app would you be open to contributing to connect?
