### ISSUE TITLE
Webpack 5 doesn't include Node.js polyfills

### ISSUE THREAD

**Issue by joerter** [hirosystems/connect#182]
I was using @stacks/connect to build a simple React app for learning the stacks ecosystem. When hooking up authentication with the Hiro wallet, I ran into this error:

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default

Basically, webpack 5 doesn't include polyfills for stream, buffer, and crypto. To fix, I had to eject from creat react app and add these polyfills manually to the webpack.config.js file. Is there a way to address this from @stacks/connect to make it easier for future users? I would be totally willing to submit a PR for this.

Thanks!

**Comment by aulneau** [comment]
hi there! I maintain an alternative package called micro-stacks which works a bit better for newer bundlers abd tooling. Feel free to check out the react guide https://docs.micro-stacks.dev/modules/integrations/react 

I'm also on the stacks discord if you have any questions

**Comment by joerter** [comment]
Awesome! Thanks I will check it out
