### ISSUE TITLE
Missing event for wallet installation cancellation 

### ISSUE THREAD

**Issue by jjenzz** [hirosystems/connect#185]
I'm using `react-connect` but seems applicable for `connect` too.

When calling `doOpenAuth`, if it opens the Hiro Wallet Installation prompt and the user closes the dialog, there doesn't seem to be a way for the UI to reflect the fact that auth was cancelled. 

Video of issue I'm having: https://twitter.com/jjenzz/status/1485244780145688576?s=20

Any help here would be appreciated, I'm probably just missing an API somewhere.

**Comment by fbwoolf** [comment]
We expose an `onCancel` callback for you to use in `AuthOptions`: https://github.com/hirosystems/connect/blob/af54624d6389c686f9b95900290cde7d941e9c77/packages/connect/src/types/auth.ts#L48

Is this what you are looking for?

**Comment by kyranjamie** [comment]
Looks like this is only fired when wallet is installed, and the flow cancelled, rather than in cases of the connect popup.

https://github.com/hirosystems/connect/blob/3ec7fee3b14aec048e4534bc2fbe804b7933454d/packages/connect-ui/src/components/modal/modal.tsx#L29-L31

We should fire the `onCancel` event here, too.

**Comment by fbwoolf** [comment]
Got it, that makes sense. The video shows before the wallet is installed. 👍

**Comment by jjenzz** [comment]
Thanks for doing that @He1DAr. Is this available in an alpha release somewhere?

**Comment by markmhx** [comment]
@jjenzz were you able to use the new version here successfully?

**Comment by jjenzz** [comment]
@markmhx not yet, i didn't think it was released yet?

**Comment by markmhx** [comment]
It appears that this change was merged into main in January: https://github.com/hirosystems/connect/commits/main

Though it doesn't appear we bumped the version up. @andresgalante should we cut a formal release here?

**Comment by andresgalante** [comment]
Yes, lets discuss with the team how to release connect

**Comment by fbwoolf** [comment]
There are some minor illustration update issues I could do here and then release? They are changes to onboarding but in the Connect modal.

**Comment by andresgalante** [comment]
@fbwoolf absolutely, if we can bundle other small improvements it'd be great. the main issue here is figuring out how to release Connect :)

**Comment by fbwoolf** [comment]
> @fbwoolf absolutely, if we can bundle other small improvements it'd be great. the main issue here is figuring out how to release Connect :)

If I remember correctly, ...if the package version is incremented correctly before merging the change then a chore release PR will get generated to release the change. Example: https://github.com/hirosystems/connect/pull/166

**Comment by fbwoolf** [comment]
My point being here, we can just address another issue and bump the version before that merge to release this, right?

**Comment by andresgalante** [comment]
@kyranjamie can you answer Fara's question about the release of Connect?

**Comment by markmhx** [comment]
nudge @kyranjamie 👆

**Comment by markmhx** [comment]
I'm reopening so we can cut a proper release with this change.

**Comment by kyranjamie** [comment]
> My point being here, we can just address another issue and bump the version before that merge to release this, right?

Absolutely, yes.
