### ISSUE TITLE
`openSTXTransfer` return type changed

### ISSUE THREAD

**Issue by davidfant** [hirosystems/connect#190]
**Describe the bug**
`openSTXTransfer` from `@stacks/connect` used to return the TS type `FinishedTxData` looking something like:
```ts
interface FinishedTxData {
  stacksTransaction: StacksTransaction;
  txId: string;
  txRaw: string;
}
```

That seems to have changed recently. Now `txId` isn't a string but rather an object with a shape like:
```ts
interface TxIdShape {
  txid: string;
  error?: string;
  reason?: string;
}
```

**What version of Blockstack.js are you using?**
```ts
    "@stacks/connect": "^6.4.0",
    "@stacks/connect-react": "^13.0.0",
    "@stacks/network": "^3.0.0",
```

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
Connect

**To Reproduce**
1. Call `openSTXTransfer` from `@stacks/connect`
2. Console log the response

**Expected behavior**
Return `txId` as a string, like the TS types suggest

**Screenshots**
-

**Console log**
-

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Brave
 - [Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (arm64)](https://brave.com/latest/)

**Additional context**
-

**Comment by hstove** [comment]
This is due to a bug in the latest Hiro wallet. It's been fixed in https://github.com/hirosystems/stacks-wallet-web/commit/9cfa3fd52ddc28a69a9bf9bac8c7cb8662bba81e, but version `3.2.0` has not been published yet. This is my understanding - could be wrong. @kyranjamie @fbwoolf

**Comment by fbwoolf** [comment]
This should be fixed in the wallet and already released. Fixed in this PR w/ sponsored tx: https://github.com/hirosystems/stacks-wallet-web/pull/2159

**Comment by fbwoolf** [comment]
Going to close this issue bc it should be fixed in the Hiro Wallet.
