### ISSUE TITLE
Add arbitrary message signing support

### ISSUE THREAD

**Issue by beguene** [hirosystems/connect#202]
In preparation for https://github.com/hirosystems/stacks-wallet-web/issues/1051 we need to make some changes in connect to expose `signatureRequest` and `verifySignatureRequest` methods (those method names are not fixed yet)

**Comment by markmhx** [comment]
@beguene do you want to take this or should we ask @janniks?

**Comment by beguene** [comment]
> @beguene do you want to take this or should we ask @janniks?

This is already done here https://github.com/hirosystems/connect/pull/205
Closing this then.

**Comment by markmhx** [comment]
Great, shouldn't we link this issue to that PR, reopen and put on the board though?
