### ISSUE TITLE
`@stacks/connect-react` packages doesn't support react 18

### ISSUE THREAD

**Issue by kyranjamie** [hirosystems/connect#213]
Reported here https://discord.com/channels/621759717756370964/623217767356694547/967796202278092830

Need to update `package.json` peerDependencies to state `16>`

Whether or not React 18 works 🤷🏼‍♂️  I'd assume so, there aren't many breaking changes. But the peerdep should err on side of "yes".

**Comment by SaadAye** [comment]
man still no update on this ???

**Comment by janniks** [comment]
Was fixed a while back, this was just an incorrect peerDependency state
