### ISSUE TITLE
signStructuredData not in line with SIP018 specification

### ISSUE THREAD

**Issue by MarvinJanssen** [hirosystems/connect#225]
Looking at `signStructuredMessage`, I noticed that although it signs Clarity Values, it is missing parts of the specification thus resulting in different signatures.

https://github.com/hirosystems/connect/blob/1f3e94aa09a356cf8d8a0b555caeabbed120d741/packages/connect/src/signature/structuredData.ts#L24-L43

As per the current draft:
https://github.com/stacksgov/sips/blob/48a8493f19702a14258db5730fece837cd783b7a/sips/sip-018/sip-018-signed-structured-data.md#formal-specification

- `signStructuredData(D, K) = sign(messageHash(D), K)`, where:
- `messageHash(D) = sha256(structuredDataPrefix || domainHash || structuredDataHash(D))`.

The domain tuple CV and payload CV should therefore be supplied separately. The prefix is `0x534950303138`.

The domain tuple CV at the bare minimum requires:
```clarity
{
	name: (string-ascii len)
	version: (string-ascii len)
	chain-id: uint
}
```

**Comment by beguene** [comment]
I agree @aulneau, the main changes are to be made in the web wallet, but we will also have to update connect to accommodate the changes.

@markmhx I will create a new one maybe for the web wallet and link this one to it.

**Comment by beguene** [comment]
@janniks Yes I think we should stay consistent. We can do that as part of this task. cc: @markmhx @andresgalante

**Comment by MarvinJanssen** [comment]
FYI: https://github.com/stacksgov/sips/pull/57#issuecomment-1140622966

The structured data prefix has been changed to make sure that SIP018 messages can absolutely never be valid transactions. The OP has been edited.
