### ISSUE TITLE
contract deployment pending tx not displaying

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/connect#231]

**Comment by radicleart** [comment]
E.g. seeing on this tx.. https://explorer.stacks.co/txid/0x54129fffab3049ad11e16eaf63dd48fa5e06cd878c091171121dd95711badc82?chain=testnet
<img width="1381" alt="Screenshot 2022-05-30 at 13 22 43" src="https://user-images.githubusercontent.com/4384929/170991583-1bfa40d0-ebfe-4341-910b-f5ab4fca6631.png">

**Comment by janniks** [comment]
Is this a connect or explorer bug?

**Comment by radicleart** [comment]
Explorer I think.
