### ISSUE TITLE
Arbitrary Message Signing with wrong account

### ISSUE THREAD

**Issue by dr-bizz** [hirosystems/connect#243]
Hey, I'm setting up Arbitrary Message Signing with Hiro using the openSignatureRequestPopup function.

The popup shows as normal and signs the message. However, the wallet that popups show as signing the message isn't the wallet I authenticated with the app. It shows the wallet to which the browser is connected, not what the application is connected to.

I saw that you could pass in "stxAddress", but this still signs the message with the wrong wallet.

Many thanks

**Comment by janniks** [comment]
@markmhx have you looked into this issue? (Might be outdated at this point)

**Comment by markmhx** [comment]
It appears we fixed this issue with https://github.com/hirosystems/stacks-wallet-web/issues/2463, so I presume we can close it here on the Connect side.
