### ISSUE TITLE
In the authentication modal clicking on Xverse opens Leather if both extensions are installed

### ISSUE THREAD

**Issue by pradel** [hirosystems/connect#350]
**Describe the bug**

In the authentication modal clicking on Xverse opens Leather if both extensions are installed

**To Reproduce**

1. Go to https://app.sigle.io/login
2. Click on "Connect wallet"
3. Click on "Connect" in the Xverse session
4. See that Leather is opened

**Expected behavior**

Xverse to open instead of Leather.

**Screenshots**

![Screenshot 2023-12-21 at 00 38 46](https://github.com/hirosystems/connect/assets/5749437/aba96217-a0a7-4781-82a5-f314a6b6270b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by janniks** [comment]
Hmm, that's bad. Will fix first thing tomorrow. Maybe a later fix changed the behavior again here, I'm sure it worked at some commit.

🙏🏻
