### ISSUE TITLE
Custom wallet provider connect

### ISSUE THREAD

**Issue by fess-v** [hirosystems/connect#356]
It would be great if it was possible to connect with different wallet providers like https://asigna.gitbook.io/asigna/stacks-multisig/quickstart/interacting-with-dapps
It can also solve the problem of wallets interfering with each other, like if users have Leather and Xverse installed and want to connect Leather but Xverse pops up by default or vice versa.
For now, it is not possible to use the Asigna extension to connect to some websites like https://lockstacks.com/sign-in?chain=mainnet
 
 Thanks a lot in advance!

**Comment by janniks** [comment]
This should now be possible via Connect. We can add Asigna directly, and if the extension is installed, it will now show up in Connect (automatically assuming the webbtc_provider is injected by the extension).
Will add documentation soon, for now feel free to DM me. Code here: https://github.com/hirosystems/connect/pull/341
