### ISSUE TITLE
Add option to use custom Gaia hub URL

### ISSUE THREAD

**Issue by muneebm** [hirosystems/connect#82]
I agree that it's confusing for a new user to see the [Gaia hub selection screens](https://forum.blockstack.org/t/user-choice-of-gaia-hub-now-available-during-onboarding/7026) during onboarding, but can we add an auth option for the app to pass in a custom Gaia hub URL. This gives app developers the flexibility to use app specific Gaia hubs without confusing the user much.

Add `customGaiaHubUrl` to `AuthOptions`
https://github.com/blockstack/connect/blob/3a5fa4582aa4c8db9fa4ee94926c607577eeac91/src/auth.ts#L12-L24

It might also be helpful to add a section in "How It Works" to explain where the data is getting stored.

**Comment by markmhx** [comment]
@hstove how well are we currently set up with the Blockstack App to support something like this ahead of general release?

**Comment by hstove** [comment]
It will require some work - not impossible, but not easy.

Although, I'm **very strongly** inclined to suggest we do this as a migration tool, **not** during onboarding. That gives us the best of both worlds - it doesn't confuse onboarding, and it's an actually viable process for existing users, who stand to benefit more from a custom Gaia hub.

**Comment by markmhx** [comment]
@muneebm is the need to set a custom Gaia hub URL an upgrade blocker for xordrive?

**Comment by muneebm** [comment]
@markmhx I am still using PBC hub for xordrive, but is planning to run my own hub for next update, before Stack 2.0 release. 
I'd say, if it doesn't delay your plans for general release, it'd be helpful for a lot of developers, now that a lot of discussions are happening  around business models and monetization. 
Also, I don't think we need to make any changes to the onboarding screens, just providing an option to pass in the custom hub URL and making the changes required in app.blockstack.org (the authenticator) to support the custom hub would be enough. We are not stating anywhere in the onboarding screens that the data is being stored in PBC hub. As the end user is trusting the app developer anyway to store their data securely, I think, it doesn't matter to them if the data is stored in PBC hub or a custom hub. This way we can keep the onboarding flow relatively simple, at the same time giving the app developer the option to use custom Gaia hub.

**Comment by markmhx** [comment]
Thanks for the info; that's good to know you aren't currently relying on a custom hub so this wouldn't be a breaking release per se. 

I'd recommend that we try to prioritize this work soon but not treat it as a blocker for general release. My understanding is that you're correct this wouldn't entail any user-facing UI changes, but it would require some extra under-the-hood work to ensure the custom Gaia hub works properly.

**Comment by markmhx** [comment]
@HariniRajan397 @wilsonbright You'll need to tackle this issue for Connect in addition to [the related one for the Stacks Wallet](https://github.com/blockstack/stacks-wallet-web/issues/1145) (or legacy Blockstack Connect, should you go that route) to accomplish Gaia hub URL passing during authentication.
